### ISSUE TITLE
Problem with build, missing module.exports

### ISSUE THREAD

**Issue by ZaDarkSide** [Naddiseo/babel-plugin-mjsx#14]
Running `babel src --out-dir lib` from `package.json`

Outputs to `lib/index.js`

The end of the file looks like this:

``` js
...
function D(v) {
    console.log(JSON.stringify(v, null, '\t'));
}

;
```

The problem is that the newly built file `index.js` doesn't contains at the end of the file this:

``` js
module.exports = exports.default;
```

This breaks using this plugin in Babel with Webpack (Babel Standalone) with this error:
`Error: Plugin 0 specified in "foreign" provided an invalid property of "default"`

Adding manually `module.exports = exports.default;` at the end of the file fixes this issue.

Also the `function D(v)` doesn't seems to be used anywhere and can be removed.

**Comment by Naddiseo** [comment]
Hi, could you provide me with a webpack script to reproduce this? I have a feeling the issue you're experiencing is because of a webpack configutation problem.

**Comment by ZaDarkSide** [comment]
I'm using https://github.com/Daniel15/babel-standalone

In `src/index.js` add your plugin to the list then do a `gulp build`, after that using the compiled file try to load a file which uses `msx`.

**Comment by Naddiseo** [comment]
Okay, so this isn't a bug with mjsx; the problem you're having is because babel-standalone doesn't understand or use the babel import/require system, and instead uses node's `require`. An incorrect solution would be to use `require('babel-plugin-mjsx').default` in your config file, the correct solution would be to report a bug to babel-standalone so that they use a babel compatible import system.

The `D()` function is something I use when debugging.

**Comment by ZaDarkSide** [comment]
Using `require('babel-plugin-mjsx').default` indeed fixes the problem.
I will forward this problem to the Babel Standalone project maintainer.
We can now close this issue.

You can track this issue further here:
https://github.com/Daniel15/babel-standalone/issues/27
