### ISSUE TITLE
Output should ignore whitespace characters

### ISSUE THREAD

**Issue by sebastiansandqvist** [Naddiseo/babel-plugin-mjsx#8]
When there are components such as:

``` javascript
<div>
    <span>foo</span>
</div>
```

the output should be a `div` with a child `span`, rather than a div with children `['\n\t', span, '\n']`

A lot of times I find things like this in the output mjsx: `\n\t\t\t\t\t\t\t` because of whatever indentation I chose to use. Those are a few wasted bytes since they are no different from a space, but the bigger issue is that the output would be more predictable without any whitespace children (unless explicitly specified as such, like `<span>{' '}</span>`). Common issues like inline-block elements getting extra spacing because of whitespace characters would be eliminated, and the output would be cleaner.

What do you think of a change like this?

Edit: some discussion on React's jsx regarding whitespace
- https://github.com/facebook/react/issues/65
- https://github.com/facebook/react/pull/480

**Comment by Naddiseo** [comment]
Originally it was like the react one, where leading and trailing new lines were stripped, and (I think) all other white space was replace with spaces. I changed it to the current implementation because of <textarea>: html spec says anything between it's tags, new lines and all, is considered default value.

**Comment by sebastiansandqvist** [comment]
What was the rationale for changing it to follow the html spec? There are many differences between jsx and html, and the handling of whitespace in React's jsx was one of my favorite things about it. I think that there is also value in having consistency with the way other jsx transformers handle whitespace. Would you be open to reverting the change to whitespace handling here?

**Comment by Naddiseo** [comment]
I see github ate some of my comment. The main reason why is because of the textarea tag, whose value is whatever is between its tags, including whitespace.

I am not opposed to reverting that particular change, as I made it on a whim without much thought, however, I think I'll dig through those react threads, and the html spec a little further before I do change it back.

**Comment by sebastiansandqvist** [comment]
Hadn't thought about textareas. Now that you mention it, `<pre>` tags and anything with `whitespace: pre` would also need its whitespace preserved. I think that for those cases, though, it would be fine to explicitly add the whitespace as a string. Something like:

``` jsx
<pre>
{`
     foo
           bar
`}
</pre>
```

Cases like the above will be relatively rare, and in that case the syntax makes it clear that whitespace is important in that tag.

**Comment by Naddiseo** [comment]
Good argument. The issue then becomes: where should the line be drawn between code and data? In your `<pre>` example, I'd argue that the contents are data, and as such do not belong inside the code tags. However, with `<textarea>`, I would argue (in the context of JSX), that it's value is part of the code, so that adding explicit whitespace in the code segments are required.

**Comment by sebastiansandqvist** [comment]
That is a good point, and I'll concede that for the `<pre>` example, my suggestion isn't ideal. But because that case is so rare, I think it would be worthwhile. This is something I run into frequently:

``` jsx
const Pricetag = {
    view(ctrl, props, children) {
        return (
            <div>
                <Icon name='pricetag'/><div className='pricetag'>
                    {children}
                </div>
            </div>
        );
    }
};
```

_Note: `.pricetag` and `Icon` are both `inline-block`_
I would like to be able to put `.pricetag` on the next line where it would naturally go, but if I did I would have to set the parent font size to 0 and then reset the `.pricetag` font size to what it was before (or some similar hack to get rid of the whitespace).
